### ISSUE TITLE
solr for version 3.3

### ISSUE THREAD

**Issue by oden08** [vrchost/rooibos#11]
Trying to install mdid 3.3 on (while updating the installation doc you have out there - if nothing else but for my own documentation) and notice in the doc you reference solr4 but in the rooibos file structure you reference solr7 now.  Can you tell me what is the preferred solr7 version?

**Comment by knabar** [comment]
Apologies for missing to include the correct solr installation instructions, I'll add them as soon as I can.

**Comment by knabar** [comment]
I updated the documentation to include the installation and configuration steps for solr 7: https://github.com/vrchost/rooibos/tree/master/resources/docs/installation

Please check out both of those sections.  If you run into any issues, please let me know so I can amend the instructions.
