### ISSUE TITLE
DesktopMediaViewer.air cert expired in October 2017, wants to "upgrade" to older version.

### ISSUE THREAD

**Issue by mepartain** [vrchost/rooibos#5]
Can you re-sign DesktopMediaViewer.air with a new cert, please?  I have to roll back the system clock in order to install it with the currently incorporated cert.

Also, on a less urgent note, it wants to "upgrade" to version 1.01.x (even though your version is 1.02.x).

**Comment by knabar** [comment]
I don't have access to a dev environment to re-issue the DesktopMediaViewer distributable right now.  A replacement viewer is in the works and should be available in the next few months, until then changing the system clock during install is the easiest way to go.

**Comment by knabar** [comment]
Closing as the Desktop MediaViewer is now officially no longer supported
